### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by vlrevolution** [afterlogic/nextcloud-connector#17] opened 2021-04-09 10:01 UTC
Update to Nextcloud 21.0.1 broke my Afterlogic integration. 

https://cloud.url.com/apps/afterlogic/ is throwing Internal Server Error

Error log shows:
Error: Call to undefined method GuzzleHttp\Utils::chooseHandler()

Here is the detailed error log:
{"reqId":"PoMPdfir6qBWdQEeEzW8","level":3,"time":"2021-04-09T12:57:39+03:00","remoteAddr":"redacted","user":"redacted","app":"index","method":"GET","url":"/apps/afterlogic/","message":{"Exception":"Error","Message":"Call to undefined method GuzzleHttp\\Utils::chooseHandler()","Code":0,"Trace":[{"file":"/var/www/webmail/vendor/guzzlehttp/guzzle/src/HandlerStack.php","line":42,"function":"GuzzleHttp\\choose_handler"},{"file":"/var/www/webmail/vendor/guzzlehttp/guzzle/src/Client.php","line":65,"function":"create","class":"GuzzleHttp\\HandlerStack","type":"::"},{"file":"/var/www/nextcloud/lib/private/Http/Client/ClientService.php","line":62,"function":"__construct","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/lib/private/OCS/DiscoveryService.php","line":55,"function":"newClient","class":"OC\\Http\\Client\\ClientService","type":"->"},{"file":"/var/www/nextcloud/lib/private/Server.php","line":1264,"function":"__construct","class":"OC\\OCS\\DiscoveryService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":155,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php","line":118,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":122,"function":"offsetGet","class":"Pimple\\Container","type":"->"},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":137,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":434,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":109,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":459,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":431,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"array_map"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":109,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":459,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":146,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"file":"/var/www/nextcloud/apps/provisioning_api/lib/Capabilities.php","line":50,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/nextcloud/lib/private/CapabilitiesManager.php","line":72,"function":"getCapabilities","class":"OCA\\Provisioning_API\\Capabilities","type":"->"},{"file":"/var/www/nextcloud/lib/private/Template/JSConfigHelper.php","line":183,"function":"getCapabilities","class":"OC\\CapabilitiesManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/TemplateLayout.php","line":211,"function":"getConfig","class":"OC\\Template\\JSConfigHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Template.php","line":183,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":210,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":172,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/functions.php","Line":61,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0","version":"21.0.1.1","id":"607025c3d14fb"}

**Comment by afterlogic-support** [comment] 2021-04-09 10:08
Can you let us know which WebMail version you're using? You can find that in VERSION file found in root WebMail directory.

Thanks.

**Comment by vlrevolution** [comment] 2021-04-09 10:09
8.6.0-build-a3

**Comment by vlrevolution** [comment] 2021-04-09 10:12
I see it is not the latest version. Should I update, is latest version working?

**Comment by afterlogic-support** [comment] 2021-04-09 11:34
> Update to Nextcloud 21.0.1 broke my Afterlogic integration.

I wasn't able to upgrade my Nextcloud test install (v21.0.0.18):

![nextcloud-update-fails](https://user-images.githubusercontent.com/16918936/114173760-55b7d600-9940-11eb-999b-4b2365041a7c.png)
and there's nothing helpful in the logs. Going to try installing a blank copy of 21.0.1 and see how things work there.

> I see it is not the latest version. Should I update, is latest version working?
> Is this the correct docs to upgrade from 8.6.0-build-a3 to 8.8.0.rc3-build-a3?
> https://afterlogic.com/docs/webmail-lite-8/installation/upgrading-instructions

Upgrading to the latest version is worth a shot indeed, and yes those are valid instructions.

Also I'm curious if WebMail itself works if it's opened directly, and it's just the integration that doesn't work?

**Comment by vlrevolution** [comment] 2021-04-09 11:48
I had the same error when I first tried to upgrade. I clicked retry installation at the top of the same page and it worked the second time.

The actual WebMail when opened directly by url works. So this has to do with the integration I think.

**Comment by afterlogic-support** [comment] 2021-04-09 12:16
I was able to reproduce the issue with Nextcloud 21.0.1 and WebMail 8.6.0, upgrading to 8.8.0 didn't fix it.
Will try to narrow this down, apparently something has changed in integration API of Nextcloud.
I'll post back here once there are news.

**Comment by afterlogic-support** [comment] 2021-04-09 12:44
For now, a quick workaround is to set **AllowPostLogin** to **true** in `data/settings/modules/Core.config.json`, and put an empty value for "File path to Afterlogic WebMail installation:" in Nextcloud's "Additional Settings". That will result in sending login credentials to WebMail via POST rather than directly via PHP API so the issue shouldn't occur.

We continue investigating this. Will be in touch once there's more info.

**Comment by afterlogic-support** [comment] 2021-04-12 09:07
UPD: Investigation shows that it's the following code in the integration app resulting in error:
```php
$sFile = rtrim(trim($sPath), '\\/').'/system/autoload.php';
include_once $sFile;
\Aurora\System\Api::Init(true);
```

It's our standard code for invoking PHP API of WebMail, and the code works just fine when run as standalone script, the error occurs when it's used in Nextcloud application. From the error itself, it looks like Nextcloud uses GuzzleHttp library as well as we do, but probably a different version so it conflicts with our autoloader.

At the moment, we can't think of any good solution here. Most likely, we'll be eliminating the use of PHP API altogether and switch over to Web API. It will, however, put some limitations on using Nextcloud and Webmail in different domains. Should that be the case, POST login per my previous message remains a decent alternative.

Will post back here with more news.

**Comment by afterlogic-support** [comment] 2021-04-14 14:44
Made some good progress on replacing the use of PHP API with Web API in the connector, removing the possibility of this particular issue or any similar ones. 
We'll need to do some more testing, and settings panel will need some changes to be made - filesystem path of WebMail installation is no longer needed, instead we'll be adding a selection between web API call (used by default) and POST login (used if WebMail and Nextcloud are in different domains or on different servers). 
Most likely, an updated connector will be published by the end of the week.

**Comment by vlrevolution** [comment] 2021-04-14 15:27
Thanks for your hard work! Looking forward to it and using POST api in the
meantime as per your suggestion

**Comment by afterlogic-support** [comment] 2021-04-15 11:00
OK we've just released a rewritten version of Nextcloud connector. In this version, Web API is used by default. Those upgrading from previous versions of the connector won't need to reconfigure anything, it'll work for them as expected - assuming they have Nextcloud and WebMail in the same domain. For other cases, POST login is still supported, of course.

Please let us know if this helps you. Thanks!

**Closed** 2021-04-21 08:20 UTC
