### ISSUE TITLE
Nextcloud 19 Support

### ISSUE THREAD

**Issue by JoeKun** [afterlogic/nextcloud-connector#12] opened 2020-07-16 21:53 UTC
The AfterLogic Nextcloud app is not officially supported on Nextcloud 19.

Can you guys look into what it would take to make it officially supported on Nextcloud 19?

Thanks.

**Comment by afterlogic-support** [comment] 2020-07-17 07:40
Sure, will look into this within next few days. Thanks.

**Comment by afterlogic-support** [comment] 2020-07-20 08:49
It appears that v19 of Nextcloud has some major issues preventing our app from working correctly.
Specifically, all the requests to /index.php/apps/afterlogic/ are redirected over to /index.php/apps/files/ so it's not possible to run the app or save its settings in Nextcloud admin area. 
With Nextcloud 18.0.7, it's all working as expected (FWIW, 18.0.7 doesn't state there's an update, unless you switch to Beta channel).

We'll keep an eye on Nextcloud 19 releases and once this is fixed, we'll update the application. If you wish to submit a ticket to [Nextcloud issue tracker](https://github.com/nextcloud/server/issues), that could help a lot.

**Comment by afterlogic-support** [comment] 2020-07-20 09:04
Follow-up: there's still a chance the issue is on our app side, and the application itself needs updating/rewriting, so we're looking into that one, too.

**Comment by zecman** [comment] 2020-07-27 19:29
thanks, highly appreciated

**Comment by kolosek** [comment] 2020-08-02 06:52
@afterlogic-support Yes, thank you. Looking forward to it.

**Comment by zecman** [comment] 2020-08-02 08:04
in fact the standard email plugin of nextcloud is not able to handle "real"mailboxes... one of my clients has more than 16,000 emails in his inbox... webmail-lite is the only webmail solution i know that can handle this with ease.

**Comment by afterlogic-support** [comment] 2020-08-03 10:59
Just wanted to let you know that we've reached a good progress at rewriting the application to make it compatible with Nextcloud 19 - and we should be able to release it within a couple of days. Thank you for your patience.

**Comment by zecman** [comment] 2020-08-03 15:13
Huge thank you to the @afterlogic-support!

**Comment by afterlogic-support** [comment] 2020-08-04 13:19
We've just released Afterlogic connector for nextCloud compatible with version 19; versions 17 and 18 are supported by the app package as well.

If you encounter any issues with it, please post at [this issue tracker](https://github.com/afterlogic/nextcloud-connector/issues). Thank you!

**Comment by zecman** [comment] 2020-08-05 12:15
Since I have Afterlogic Webmail running inside a docker container with a different subdomain, I get blocked by CSP... Do you know how to get rid of this?

**Comment by afterlogic-support** [comment] 2020-08-05 12:20
@zecman there's a fix for that, please see [this topic](https://github.com/afterlogic/nextcloud-connector/issues/13)
and it will be included in the updated package shortly
thank you!

**Closed** 2020-08-10 08:32 UTC
